### ISSUE TITLE
Card Number' is not in the correct format.

### ISSUE THREAD

**Issue by seabdejelil** [apaleo/api#310] opened 2020-04-29 11:49 UTC
I try to test the reservations but I always receive. 
{
  "messages": [
    "'Card Number' is not in the correct format."
  ]
}
despite that we have a detokonization solution and we send the carnumber with the right format.

**Comment by bennetone** [comment] 2020-05-04 15:24
duplicate of https://github.com/apaleo/api/issues/312

**Closed by bennetone** 2020-05-04 15:24 UTC
Labels: duplicate
