### ISSUE TITLE
Adyen Authentication API Key Updation

### ISSUE THREAD

**Issue by limehome-dev** [apaleo/api#120] opened 2019-04-18 09:41 UTC
## Question

How can we update the new _Adyen Authentication API key_ for integration with Apaleo?

## Background

We have accidentally changed the API Authentication key for the user that Apaleo is using for integration with Adyen. Now, in order to keep the integration running without errors, we suppose we need to get the API key updated at your end. Otherwise, It can create problems.

**Comment by pgrm** [comment] 2019-04-18 10:24
possible duplicate of https://github.com/apaleo/api/issues/119

hello @patrickHermannLimeHouse the link which I've provided in https://github.com/apaleo/api/issues/119#issuecomment-483759268 should work - at https://app.apaleo.com/account/payment you can see the current configuration and also change it. Does that answer your question?

**Comment by ozonni** [comment] 2019-04-18 10:36
@patrickHermannLimeHouse you should create new Adyen web user for your integration and not to re-use web users that are used for other integrations. Just to avoid such problems when you change something for your needs.

As i can see, we don't store API key for this account, so changing it should be fine. Although changing web user password can break our integration with Adyen.

**Comment by patrickHermannLimeHouse** [comment] 2019-04-18 12:21
Thanks for the clear and detailed answer.

> @patrickHermannLimeHouse you should create new Adyen web user for your integration and not to re-use web users that are used for other integrations. Just to avoid such problems when you change something for your needs.
> 
> As i can see, we don't store API key for this account, so changing it should be fine (Although i don't recommend it). Although changing web user password can break our integration with Adyen.

**Closed** 2019-05-24 14:23 UTC

**Comment by limehome-dev** [comment] 2019-05-28 09:23
we where forced to change the adyen password yesterday and we where not able to change the password to the old one again. 
can you please check if there are any issues with your Adyen integration since yesterday? 
If yes, whats the problem?
Do we have to change the password in our account now?

**Comment by swiesener** [comment] 2019-05-28 10:53
I assume that you have changed the password for your Adyen extranet login. This password has nothing to do with the web service users API keys, etc. The system should be working fine - I tested a booking with CC a few mins ago.
